[build]
  command = "npm install --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

# Configure secrets scanning to ignore expected environment variables
# NEXT_PUBLIC_SNIPCART_API_KEY is a public key that's safe to expose
[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SNIPCART_API_KEY,PRINTFUL_API_KEY"

[context.deploy-preview.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SNIPCART_API_KEY,PRINTFUL_API_KEY"

[context.branch-deploy.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SNIPCART_API_KEY,PRINTFUL_API_KEY"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js
[[redirects]]
  from = "/_next/image"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
