[build]
  command = "npm install --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

# Configure secrets scanning to ignore false positives in code patterns
# These are environment variable NAMES in code, not actual secret values
[context.production.environment]
  SECRETS_SCAN_OMIT_PATHS = "src/lib/database/config.ts,src/lib/env-validation.ts,src/lib/client-env-validation.ts,src/lib/printful-client.ts,src/lib/create-order-v1.ts,src/lib/create-order.ts,.next/**,*.nft.json,*.map,*.js.map,*.pack"

[context.deploy-preview.environment]
  SECRETS_SCAN_OMIT_PATHS = "src/lib/database/config.ts,src/lib/env-validation.ts,src/lib/client-env-validation.ts,src/lib/printful-client.ts,src/lib/create-order-v1.ts,src/lib/create-order.ts,.next/**,*.nft.json,*.map,*.js.map,*.pack"

[context.branch-deploy.environment]
  SECRETS_SCAN_OMIT_PATHS = "src/lib/database/config.ts,src/lib/env-validation.ts,src/lib/client-env-validation.ts,src/lib/printful-client.ts,src/lib/create-order-v1.ts,src/lib/create-order.ts,.next/**,*.nft.json,*.map,*.js.map,*.pack"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for Next.js
[[redirects]]
  from = "/_next/image"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"

[[redirects]]
  from = "/_ipx/*"
  query = {q = ":quality", url = ":url", w = ":width"}
  status = 200
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
